services:
  domposbi:
    container_name: domposbi
    # No image available, build from source
    build:
      context: ./src
    restart: unless-stopped
    environment:
      - DOCKER_COMPOSE_PROJECTS_DIR
      - BACKUP_DIR
      - CRON_SCHEDULE
      - GIT_REPO_URL_FOR_SIMBASHLOG_NOTIFIER
      - KEYWORD_TO_EXCLUDE_FROM_BACKUP
      - KEEP_BACKUPS
      # Optional
      - ENABLE_DEBUG_MODE
      - ENABLE_DRY_RUN
    volumes:
      # Logs - Comment out to disable logging to host
      - type: bind
        source: ./volumes/logs
        target: /var/log/cron # Change to '/var/log' if all logs should be saved
        bind:
          create_host_path: true
      # simbashlog notifier config - Comment out if no simbashlog notifier is used
      - type: bind
        source: ./volumes/config
        target: /root/.config/simbashlog-notifier
        bind:
          create_host_path: true
      # Docker socket - This is needed to shutdown and restart the containers during the backup process
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      # Directory with the Docker Compose projects
      - type: bind
        source: $DOCKER_COMPOSE_PROJECTS_DIR
        target: /data/projects
        read_only: true
      # Directory to store the backups
      - type: bind
        source: $BACKUP_DIR
        target: /data/backups
        bind:
          create_host_path: false
